/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppHome {}
  interface AppNav {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface AppRouter {}
  interface TestGenerate {
    'match': MatchResults;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {}
  var HTMLAppNavElement: {
    prototype: HTMLAppNavElement;
    new (): HTMLAppNavElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {}
  var HTMLAppRouterElement: {
    prototype: HTMLAppRouterElement;
    new (): HTMLAppRouterElement;
  };

  interface HTMLTestGenerateElement extends Components.TestGenerate, HTMLStencilElement {}
  var HTMLTestGenerateElement: {
    prototype: HTMLTestGenerateElement;
    new (): HTMLTestGenerateElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-nav': HTMLAppNavElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-router': HTMLAppRouterElement;
    'test-generate': HTMLTestGenerateElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppNav {}
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface AppRouter {}
  interface TestGenerate {
    'match'?: MatchResults;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-nav': AppNav;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-router': AppRouter;
    'test-generate': TestGenerate;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-nav': LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-router': LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
      'test-generate': LocalJSX.TestGenerate & JSXBase.HTMLAttributes<HTMLTestGenerateElement>;
    }
  }
}


