/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppCard {}
  interface AppCardContent {}
  interface AppCardDivider {}
  interface AppCardHeader {
    'class': string;
    'str': string;
  }
  interface AppHome {}
  interface AppNav {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface AppRouter {}
  interface TestGenerate {
    'match': MatchResults;
  }
}

declare global {


  interface HTMLAppCardElement extends Components.AppCard, HTMLStencilElement {}
  var HTMLAppCardElement: {
    prototype: HTMLAppCardElement;
    new (): HTMLAppCardElement;
  };

  interface HTMLAppCardContentElement extends Components.AppCardContent, HTMLStencilElement {}
  var HTMLAppCardContentElement: {
    prototype: HTMLAppCardContentElement;
    new (): HTMLAppCardContentElement;
  };

  interface HTMLAppCardDividerElement extends Components.AppCardDivider, HTMLStencilElement {}
  var HTMLAppCardDividerElement: {
    prototype: HTMLAppCardDividerElement;
    new (): HTMLAppCardDividerElement;
  };

  interface HTMLAppCardHeaderElement extends Components.AppCardHeader, HTMLStencilElement {}
  var HTMLAppCardHeaderElement: {
    prototype: HTMLAppCardHeaderElement;
    new (): HTMLAppCardHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {}
  var HTMLAppNavElement: {
    prototype: HTMLAppNavElement;
    new (): HTMLAppNavElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {}
  var HTMLAppRouterElement: {
    prototype: HTMLAppRouterElement;
    new (): HTMLAppRouterElement;
  };

  interface HTMLTestGenerateElement extends Components.TestGenerate, HTMLStencilElement {}
  var HTMLTestGenerateElement: {
    prototype: HTMLTestGenerateElement;
    new (): HTMLTestGenerateElement;
  };
  interface HTMLElementTagNameMap {
    'app-card': HTMLAppCardElement;
    'app-card-content': HTMLAppCardContentElement;
    'app-card-divider': HTMLAppCardDividerElement;
    'app-card-header': HTMLAppCardHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-nav': HTMLAppNavElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-router': HTMLAppRouterElement;
    'test-generate': HTMLTestGenerateElement;
  }
}

declare namespace LocalJSX {
  interface AppCard {}
  interface AppCardContent {}
  interface AppCardDivider {}
  interface AppCardHeader {
    'class'?: string;
    'str'?: string;
  }
  interface AppHome {}
  interface AppNav {}
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface AppRouter {}
  interface TestGenerate {
    'match'?: MatchResults;
  }

  interface IntrinsicElements {
    'app-card': AppCard;
    'app-card-content': AppCardContent;
    'app-card-divider': AppCardDivider;
    'app-card-header': AppCardHeader;
    'app-home': AppHome;
    'app-nav': AppNav;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-router': AppRouter;
    'test-generate': TestGenerate;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-card': LocalJSX.AppCard & JSXBase.HTMLAttributes<HTMLAppCardElement>;
      'app-card-content': LocalJSX.AppCardContent & JSXBase.HTMLAttributes<HTMLAppCardContentElement>;
      'app-card-divider': LocalJSX.AppCardDivider & JSXBase.HTMLAttributes<HTMLAppCardDividerElement>;
      'app-card-header': LocalJSX.AppCardHeader & JSXBase.HTMLAttributes<HTMLAppCardHeaderElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-nav': LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-router': LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
      'test-generate': LocalJSX.TestGenerate & JSXBase.HTMLAttributes<HTMLTestGenerateElement>;
    }
  }
}


